const Courses =[
   
    {
        id: "1",
        title: "Sem1",
        image: require("../../assets/sem1.jpg"),
        description:"CSE Departmant",        
        course1: "C programming",
        course2: "Physics",
        course3: "Health and Fitness",
        course4: "Professional Communication",
        course5: "Mathematics",
    },
    {
        id: "2",
        title: "sem2",
        image: require("../../assets/sem2.png"),
        description: "CSE Departmant",
        course1: "C programming",
        course2: "Chemistry",
        course3: "EVS",
        course4: "Professional Communication",
        course5: "Mathematics",
    },
    {
        id: "3",
        title: "sem3",
        image: require("../../assets/sem3.jpeg"),
        description: "CSE Departmant",
        course1: "Logic Design",
        course2: "Python",
        course3: "OOP with C++",
        course4: "Career Skills",
        course5: "Discrete Mathematics",
    },
    {
        id: "4",
        title: "sem4",
        image: require("../../assets/sem4.jpeg"),
        description: "CSE Departmant",
        course1: "Finite Automata",
        course2: "Design and Analysis of algorithms",
        course3: "JAVA Programming",
        course4: "",
        course5: "",
    },
    {
        id: "5",
        title: "sem5",
        image: require("../../assets/sem5.png"),
        description: "CSE Departmant",
        course1: "Operating System",
        course2: "Design and Analysis of Algorithms",
        course3: "DBMS",
        course4: "System Software",
        course5: "Career Skills",
    },
    {
        id: "6",
        title: "sem6",
        image: require("../../assets/sem6.jpeg"),
        description: "CSE Departmant",
        course1: "Software Engineering",
        course2: "Full Stack Web Development",
        course3: "Compiler Design",
        course4: "Computer Networks-I",
        course5: "Career Skills",
    },
    {
        id: "7",
        title: "sem7",
        image: require("../../assets/sem7.png"),
        description: "CSE Departmant",
        course1: "Computer Networks-II",
        course2: "Software Verification and Validation",
        course3: "Image Processing",
        course4: "ML",
        course5: "Major Project",
    },
    {
        id: "8",
        title: "sem8",
        image: require("../../assets/sem8.png"),
        description: "CSE Departmant",
        course1: "Soft Computing",
        course2: "Cryptography",
        course3: "AI",
        course4: "Disaster Management",
        course5: "Major Project",
    }
]
export default Courses